/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/choose-role` | `/choose-role`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/help-center` | `/help-center`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/phone-number` | `/phone-number`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verification-code` | `/verification-code`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/likes`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/matches`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/standouts`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/choose-role` | `/choose-role`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/help-center` | `/help-center`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/phone-number` | `/phone-number`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verification-code` | `/verification-code`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/likes`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/matches`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/standouts`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/choose-role${`?${string}` | `#${string}` | ''}` | `/choose-role${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/help-center${`?${string}` | `#${string}` | ''}` | `/help-center${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/phone-number${`?${string}` | `#${string}` | ''}` | `/phone-number${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verification-code${`?${string}` | `#${string}` | ''}` | `/verification-code${`?${string}` | `#${string}` | ''}` | `/tabs/account${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs/likes${`?${string}` | `#${string}` | ''}` | `/tabs/matches${`?${string}` | `#${string}` | ''}` | `/tabs/standouts${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/choose-role` | `/choose-role`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/help-center` | `/help-center`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/phone-number` | `/phone-number`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verification-code` | `/verification-code`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/likes`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/matches`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/standouts`; params?: Router.UnknownInputParams; };
    }
  }
}
